'use strict';

/**
 * Codexterity — manifest.json validation (Phase 4 M1, D-0001-4)
 * -----------------------------------------------------------------
 * manifest.json is GENERATED by tools/palette/emit-theme.mjs (owned by
 * another worker); this module only validates the shape it promises, it
 * never writes one. Validation is intentionally strict: an unknown
 * top-level key is an error, not a warning, so a typo in the generator (or
 * a hand-edited theme someone ships) fails loudly at load time instead of
 * being silently ignored and shipping a theme that quietly does less than
 * its author thinks it does.
 *
 * This module does not touch the filesystem. `validateManifest` checks the
 * parsed object's shape only; the caller (injector/theme-loader/index.js)
 * is responsible for confirming that `files.css`, `files.syntax`, and every
 * `assets[].path` actually exist in the package and match their declared
 * sizes, because only the caller knows whether it is reading a directory or
 * a .ccskin zip.
 */

const { ThemeLoadError } = require('./errors.js');
const { isSafeRelativePath } = require('./path-safety.js');

const REQUIRED_KEYS = [
  'formatVersion',
  'id',
  'name',
  'version',
  'author',
  'license',
  'description',
  'targetApp',
  'targetVersionRange',
  'verifiedAgainst',
  'files',
  'landmarks',
  'assets',
];
const ALLOWED_KEYS = new Set(REQUIRED_KEYS);

// formatVersion is the forward-compatibility hinge: it names the PACKAGE
// FORMAT (this module's contract), not the theme's own `version`. Bumping
// it is a breaking change to what a `.ccskin` is allowed to contain, so a
// loader from a different era must refuse rather than guess.
const SUPPORTED_FORMAT_VERSION = 1;

const ID_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;
// Theme `version`: dotted-numeric, 1-4 components, per this milestone's spec.
const THEME_VERSION_PATTERN = /^\d+(\.\d+){0,3}$/;
// Codex's own version, and the range bounds that are compared against it,
// are dotted-numeric but NOT semver (D-0001-4 spec) — Codex ships
// "26.727.6591.0", four components, and no upper bound on component count
// or value is assumed here.
const DOTTED_VERSION_PATTERN = /^\d+(\.\d+)*$/;
const D_MARKER_PATTERN = /^D-\d+-\d+$/;

function fail(message) {
  throw new ThemeLoadError('MANIFEST_INVALID', message);
}

/**
 * Compare two dotted-numeric version strings component-wise, treating a
 * missing trailing component as 0. Returns -1, 0, or 1.
 *
 * Deliberately NOT semver: Codex's real version string is four dotted
 * components with no notion of pre-release/build metadata, and modelling it
 * as semver would assert a structure the data does not have. This is
 * exported so a later milestone's `cdx verify` can reuse the exact
 * comparison this loader used to validate `targetVersionRange`.
 *
 * D-0001-31 — it has NO caller today and that is deliberate; see the marker at
 * the `targetVersionRange` validation below before adding one.
 */
function compareDottedVersions(a, b) {
  const partsA = a.split('.').map(Number);
  const partsB = b.split('.').map(Number);
  const len = Math.max(partsA.length, partsB.length);
  for (let i = 0; i < len; i++) {
    const x = partsA[i] || 0;
    const y = partsB[i] || 0;
    if (x < y) return -1;
    if (x > y) return 1;
  }
  return 0;
}

/**
 * Is `version` within [min, max) — min inclusive, max EXCLUSIVE, per the
 * D-0001-4 spec (this is the one place that convention is enforced).
 */
function isVersionInRange(version, range) {
  return (
    compareDottedVersions(version, range.min) >= 0 &&
    compareDottedVersions(version, range.max) < 0
  );
}

function checkDottedVersionField(value, label) {
  if (typeof value !== 'string' || !DOTTED_VERSION_PATTERN.test(value)) {
    fail(`manifest.json: ${label} must be a dotted-numeric version string (got ${JSON.stringify(value)})`);
  }
}

function validateFilesField(files) {
  if (typeof files !== 'object' || files === null || Array.isArray(files)) {
    fail('manifest.json: "files" must be an object with "css" and "syntax" keys');
  }
  const allowedFileKeys = new Set(['css', 'syntax']);
  for (const key of Object.keys(files)) {
    if (!allowedFileKeys.has(key)) {
      fail(`manifest.json: "files" has unknown key "${key}"`);
    }
  }
  for (const key of ['css', 'syntax']) {
    const value = files[key];
    if (typeof value !== 'string' || value.length === 0) {
      fail(`manifest.json: "files.${key}" must be a non-empty relative path`);
    }
    if (!isSafeRelativePath(value)) {
      fail(`manifest.json: "files.${key}" is not a safe relative path (got ${JSON.stringify(value)})`);
    }
  }
}

function validateLandmarks(landmarks) {
  if (!Array.isArray(landmarks)) {
    fail('manifest.json: "landmarks" must be an array');
  }
  landmarks.forEach((landmark, i) => {
    if (typeof landmark !== 'object' || landmark === null || Array.isArray(landmark)) {
      fail(`manifest.json: landmarks[${i}] must be an object`);
    }
    const allowedLandmarkKeys = new Set(['name', 'selector', 'governedBy', 'required']);
    for (const key of Object.keys(landmark)) {
      if (!allowedLandmarkKeys.has(key)) {
        fail(`manifest.json: landmarks[${i}] has unknown key "${key}"`);
      }
    }
    if (typeof landmark.name !== 'string' || landmark.name.length === 0) {
      fail(`manifest.json: landmarks[${i}].name must be a non-empty string`);
    }
    // Shape only — this module does not parse or validate `selector` as CSS,
    // per this milestone's spec.
    if (typeof landmark.selector !== 'string' || landmark.selector.length === 0) {
      fail(`manifest.json: landmarks[${i}].selector must be a non-empty string`);
    }
    if (landmark.governedBy !== undefined) {
      if (typeof landmark.governedBy !== 'string' || !D_MARKER_PATTERN.test(landmark.governedBy)) {
        fail(`manifest.json: landmarks[${i}].governedBy must look like "D-<plan>-<n>" (got ${JSON.stringify(landmark.governedBy)})`);
      }
    }
    if (landmark.required !== undefined && typeof landmark.required !== 'boolean') {
      fail(`manifest.json: landmarks[${i}].required must be a boolean`);
    }
  });
}

function validateAssets(assets) {
  if (!Array.isArray(assets)) {
    fail('manifest.json: "assets" must be an array');
  }
  assets.forEach((asset, i) => {
    if (typeof asset !== 'object' || asset === null || Array.isArray(asset)) {
      fail(`manifest.json: assets[${i}] must be an object`);
    }
    const allowedAssetKeys = new Set(['path', 'bytes']);
    for (const key of Object.keys(asset)) {
      if (!allowedAssetKeys.has(key)) {
        fail(`manifest.json: assets[${i}] has unknown key "${key}"`);
      }
    }
    if (typeof asset.path !== 'string' || !isSafeRelativePath(asset.path)) {
      fail(`manifest.json: assets[${i}].path is not a safe relative path (got ${JSON.stringify(asset.path)})`);
    }
    if (!Number.isInteger(asset.bytes) || asset.bytes < 0) {
      fail(`manifest.json: assets[${i}].bytes must be a non-negative integer (got ${JSON.stringify(asset.bytes)})`);
    }
  });
}

/**
 * Validate a PARSED manifest.json object against the D-0001-4 schema.
 * Throws ThemeLoadError('MANIFEST_INVALID', ...) on the first structural
 * problem found; returns the same object (unmodified) on success so the
 * caller can use it directly.
 */
function validateManifest(manifest) {
  if (typeof manifest !== 'object' || manifest === null || Array.isArray(manifest)) {
    fail('manifest.json must be a JSON object');
  }

  for (const key of Object.keys(manifest)) {
    if (!ALLOWED_KEYS.has(key)) {
      fail(`manifest.json: unknown top-level key "${key}"`);
    }
  }
  for (const key of REQUIRED_KEYS) {
    if (!(key in manifest)) {
      fail(`manifest.json: missing required field "${key}"`);
    }
  }

  if (manifest.formatVersion !== SUPPORTED_FORMAT_VERSION) {
    fail(
      `manifest.json: formatVersion ${JSON.stringify(manifest.formatVersion)} is not supported by ` +
        `this loader (expects ${SUPPORTED_FORMAT_VERSION}). This theme was built for a newer or ` +
        `older version of the Codexterity package format.`
    );
  }

  if (typeof manifest.id !== 'string' || !ID_PATTERN.test(manifest.id)) {
    fail(`manifest.json: "id" must be lowercase kebab-case (got ${JSON.stringify(manifest.id)})`);
  }
  if (manifest.id.includes('..') || manifest.id.includes('/') || manifest.id.includes('\\')) {
    // Redundant against ID_PATTERN today, but "id" is used as a directory/
    // file name downstream, and this guard is the one that actually says
    // why — kept explicit rather than relying solely on the regex.
    fail(`manifest.json: "id" must not contain a path separator or ".." (got ${JSON.stringify(manifest.id)})`);
  }

  for (const label of ['name', 'author', 'license', 'description', 'targetApp']) {
    if (typeof manifest[label] !== 'string' || manifest[label].length === 0) {
      fail(`manifest.json: "${label}" must be a non-empty string`);
    }
  }

  if (typeof manifest.version !== 'string' || !THEME_VERSION_PATTERN.test(manifest.version)) {
    fail(`manifest.json: "version" must be dotted-numeric with 1-4 components (got ${JSON.stringify(manifest.version)})`);
  }

  // D-0001-31 (Plan 0002 M4) — `targetVersionRange` and `verifiedAgainst` are
  // DECLARATIVE METADATA. Their SHAPE is validated here and their VALUES are
  // deliberately never compared against the installed Codex version, anywhere
  // in this codebase. That is a settled owner decision, not an omission:
  // refusing to apply a theme because a version number moved would remove a
  // working theme from a working app on a routine Store update, and Codex
  // updates itself on its own schedule. The project's rule is to degrade when
  // a theme CANNOT APPLY CLEANLY — which is what the landmark report in
  // injector/core/landmarks.js actually measures, version-independently — not
  // when a string changed. `isVersionInRange` below is exported and currently
  // has no caller for exactly this reason; it is the comparison a future
  // `cdx verify` would reuse, kept beside the fields it describes rather than
  // wired into the launch path. DO NOT "fix" this by adding an enforcement
  // gate, and do not add a warn-only one either. If it is ever reopened the
  // shape is already fixed: the launcher exports CDX_HOST_VERSION (only the
  // launchers may read the host version — the layer rule in
  // docs/ENGINEERING.md), the injector core compares and LOGS, and it never
  // refuses. Full reasoning: docs/plans/0002-phase-7-qa-docs-release.md
  // §"The update-resilience ruling".
  checkDottedVersionField(manifest.verifiedAgainst, 'verifiedAgainst');

  const range = manifest.targetVersionRange;
  if (typeof range !== 'object' || range === null || Array.isArray(range)) {
    fail('manifest.json: "targetVersionRange" must be an object with "min" and "max" keys');
  }
  const allowedRangeKeys = new Set(['min', 'max']);
  for (const key of Object.keys(range)) {
    if (!allowedRangeKeys.has(key)) {
      fail(`manifest.json: "targetVersionRange" has unknown key "${key}"`);
    }
  }
  checkDottedVersionField(range.min, 'targetVersionRange.min');
  checkDottedVersionField(range.max, 'targetVersionRange.max');
  if (compareDottedVersions(range.min, range.max) >= 0) {
    fail(
      `manifest.json: "targetVersionRange.min" (${range.min}) must be less than "max" (${range.max}) ` +
        `— min is inclusive, max is exclusive`
    );
  }

  validateFilesField(manifest.files);
  validateLandmarks(manifest.landmarks);
  validateAssets(manifest.assets);

  return manifest;
}

module.exports = {
  validateManifest,
  compareDottedVersions,
  isVersionInRange,
  SUPPORTED_FORMAT_VERSION,
};
